<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class QuizController extends Controller
{
    private function getQuestions()
    {
        return [
            1 => ['q' => 'Which branch of Earth Science is primarily concerned with the study of rocks, minerals, and the internal geologic processes occurring within the Earth\'s layers?', 'options' => ['A' => 'Oceanography', 'B' => 'Meteorology', 'C' => 'Geology', 'D' => 'Astronomy'], 'correct' => 'C'],
            2 => ['q' => 'The Earth is sustained by four intersecting subsystems. Which subsystem comprises all of the planet\'s liquid water, covering approximately 70% of its surface?', 'options' => ['A' => 'Geosphere', 'B' => 'Hydrosphere', 'C' => 'Atmosphere', 'D' => 'Biosphere'], 'correct' => 'B'],
            3 => ['q' => 'Earth\'s structural layers can be categorized by composition. Which of the following correctly describes the Continental Crust?', 'options' => ['A' => 'It is known as the SiMa layer, thin, dense, and primarily basaltic.', 'B' => 'It is known as the SiAl layer, thick, less dense, and primarily granitic.', 'C' => 'It is a liquid layer composed predominantly of iron and nickel.', 'D' => 'It is the dominant rock type found exclusively within the upper mantle.', 'E' => ''], 'correct' => 'B'],
            4 => ['q' => 'What specific boundary separates the Earth\'s crust from the underlying upper mantle?', 'options' => ['A' => 'Gutenberg Discontinuity', 'B' => 'Lehmann Discontinuity', 'C' => 'Mohorovicic Discontinuity (Moho)', 'D' => 'Asthenosphere'], 'correct' => 'C'],
            5 => ['q' => 'The Gutenberg Discontinuity serves as the boundary interface between which two structural layers?', 'options' => ['A' => 'The crust and the upper mantle', 'B' => 'The outer core and the inner core', 'C' => 'The lithosphere and the asthenosphere', 'D' => 'The mantle and the core'], 'correct' => 'D'],
            6 => ['q' => 'Which statement accurately differentiates the internal zones of Earth\'s core separated by the Lehmann discontinuity?', 'options' => ['A' => 'The outer core is solid peridotite; the inner core is liquid granite.', 'B' => 'The outer core is liquid iron/nickel; the inner core is solid iron/nickel.', 'C' => 'The outer core is basaltic; the inner core is granitic.', 'D' => 'The outer core behaves plastically; the inner core is completely molten.'], 'correct' => 'B'],
            7 => ['q' => 'When looking at the mechanical layers of the Earth, how do the Lithosphere and Asthenosphere interact?', 'options' => ['A' => 'The rigid lithosphere behaves as a solid layer sitting directly above the plastic, upper mantle asthenosphere.', 'B' => 'The asthenosphere is a solid crustal layer completely enclosed by the liquid lithosphere.', 'C' => 'The lithosphere is entirely liquid and sits deep beneath the semi-solid asthenosphere.', 'D' => 'They represent identical chemical layers with no distinct physical mechanical variances.'], 'correct' => 'A'],
            8 => ['q' => 'What are the explicit physical parameters or rocky designations indicated for the Mantle?', 'options' => ['A' => 'It consists exclusively of molten SiAl layer elements.', 'B' => 'It is designated as a thick shell between the core and crust, featuring Peridotite as the dominant rock type in its uppermost zone.', 'C' => 'It is completely liquid iron and nickel measuring exactly 70% of Earth\'s volume.', 'D' => 'It is an extension of the granitic continental crust.'], 'correct' => 'B'],
            9 => ['q' => 'Alfred Wegener\'s Continental Drift Theory proposed that a singular supercontinent named Pangaea rifted apart around 200 million years ago. What lines of evidence did he use to support this?', 'options' => ['A' => 'Radiometric carbon dating, seafloor renewal rates, and deep trench sonar mapping.', 'B' => 'Biological evidence, glacial evidence, and continuity of geologic features.', 'C' => 'Porosity variations, atmospheric pressure gradients, and specific gravity metrics.', 'D' => 'Strike-slip faults, reverse folding, and contact metamorphism zones.'], 'correct' => 'B'],
            10 => ['q' => 'According to Harry Hess\'s Seafloor Spreading mechanism, where is new oceanic floor continuously created?', 'options' => ['A' => 'Along deep subduction trenches', 'B' => 'Along the ocean ridge system', 'C' => 'Within subterranean limestone caves', 'D' => 'Inside the granitic continental shield'], 'correct' => 'B'],
            11 => ['q' => 'Tectonic plates interact continuously along three distinct boundary types. Which option correctly matches a boundary with its dynamic motion?', 'options' => ['A' => 'Divergent - plates crash into each other; Convergent - plates slide horizontally.', 'B' => 'Transform - plates move away from each other; Divergent - plates crash.', 'C' => 'Divergent - plates move away from each other; Transform plates slide horizontally past one another.', 'D' => 'Convergent - new oceanic rock is formed; Transform - plates move away.'], 'correct' => 'C'],
            12 => ['q' => 'What term is used to describe the slow, large-scale deformation of the Earth\'s crust that includes the uplift, faulting, and folding of mountain ranges?', 'options' => ['A' => 'Weathering', 'B' => 'Diastrophism', 'C' => 'Lithification', 'D' => 'Mass Wasting'], 'correct' => 'B'],
            13 => ['q' => 'A force that tends to affect rock structural integrity under diastrophism can be categorized into three operational expressions. What are they?', 'options' => ['A' => 'Dissolve, crystallize, or precipitate', 'B' => 'Compress, pull apart, or deform', 'C' => 'Melt, solidify, or foliate', 'D' => 'Subduct, spread, or drift'], 'correct' => 'B'],
            14 => ['q' => 'A rock unit undergoes a temporary or permanent adjustment in volume, shape, or structural integrity due to an applied force. This resulting structural adjustment is called:', 'options' => ['A' => 'Stress', 'B' => 'Strain', 'C' => 'Faulting', 'D' => 'Exfoliation'], 'correct' => 'B'],
            15 => ['q' => 'Compressive stress can cause layered bedrock to wrinkle into distinct folds. How do geologists distinguish an Anticline from a Syncline?', 'options' => ['A' => 'An anticline is an arch-shaped fold; a syncline is a trough-shaped fold.', 'B' => 'An anticline is a fractured fault line; a syncline is an unfractured zone.', 'C' => 'An anticline is caused by tension; a syncline is caused by deep planetary impacts.', 'D' => 'An anticline features horizontal sliding; a syncline features vertical dropping.'], 'correct' => 'A'],
            16 => ['q' => 'Imagine a fault cross-section where brittle fracturing has occurred. If the hanging wall block moves downward relative to the footwall block, what type of fault are you looking at?', 'options' => ['A' => 'Reverse fault', 'B' => 'Normal fault', 'C' => 'Strike-slip fault', 'D' => 'Transform fault'], 'correct' => 'B'],
            17 => ['q' => 'Along certain fault interfaces, blocks of rock slide horizontally past each other with minimal vertical movement. This type of fault is alternatively explicitly named a:', 'options' => ['A' => 'Normal fault', 'B' => 'Reverse fault', 'C' => 'Transform fault', 'D' => 'Dip-slip fault'], 'correct' => 'C'],
            18 => ['q' => 'When testing a mineral, a student rubs it across a piece of unglazed porcelain to observe the color of its fine powder. Which physical property is being assessed?', 'options' => ['A' => 'Color', 'B' => 'Cleavage', 'C' => 'Streak', 'D' => 'Luster'], 'correct' => 'C'],
            19 => ['q' => 'How is the mineral property "Luster" uniquely defined?', 'options' => ['A' => 'The ability of a mineral to resist scratching.', 'B' => 'The appearance of the mineral\'s surface in reflected light, categorized as metallic or nonmetallic.', 'C' => 'The ratio of a sample\'s weight to that of an equal volume of water.', 'D' => 'The tendency of a mineral to break along definite, smooth planes.'], 'correct' => 'B'],
            20 => ['q' => 'Which two physical properties of minerals deal specifically with how a mineral breaks?', 'options' => ['A' => 'Hardness and Crystal Form', 'B' => 'Specific Gravity and Color', 'C' => 'Cleavage (breaking along smooth planes) and Fracture (irregular breaking)', 'D' => 'Luster (light reflection) and Streak (powder color)'], 'correct' => 'C'],
            21 => ['q' => 'Igneous rocks are classified based on where their parent molten mass cooled. Why is Granite classified as an intrusive igneous rock, while Basalt is classified as extrusive?', 'options' => ['A' => 'Granite cools rapidly on Earth\'s surface; Basalt cools slowly deep underground.', 'B' => 'Granite is formed from weathered sediment particles; Basalt is formed by high pressure.', 'C' => 'Granite forms from magma that cools slowly deep beneath the surface; Basalt forms from lava that cools rapidly above the surface.', 'D' => 'Granite is a chemical sedimentary rock; Basalt is a regional metamorphic rock.'], 'correct' => 'C'],
            22 => ['q' => 'Which of the following rocks is explicitly noted in the text as the most common extrusive rock found on Earth\'s surface?', 'options' => ['A' => 'Granite', 'B' => 'Basalt', 'C' => 'Limestone', 'D' => 'Quartzite'], 'correct' => 'B'],
            23 => ['q' => 'Sediments are organized into two distinct sub-classifications based on origin. What are they?', 'options' => ['A' => 'Intrusive and Extrusive', 'B' => 'Foliated and Non-foliated', 'C' => 'Clastic/Detrital (weathered fragments) and Chemical (dissolved rock materials)', 'D' => 'Contact and Regional'], 'correct' => 'C'],
            24 => ['q' => 'Sedimentary rock formation requires a two-step process called lithification. What are these two sequential steps?', 'options' => ['A' => 'Melting and Solidification', 'B' => 'Compaction (squeezing water out) and Cementation (binding particles together)', 'C' => 'Contact Metamorphism and Regional Metamorphism', 'D' => 'Mechanical Weathering and Mass Wasting'], 'correct' => 'B'],
            25 => ['q' => 'What is the most abundant type of chemical sedimentary rock listed in your reviewer?', 'options' => ['A' => 'Carbonates (limestone and dolomite)', 'B' => 'Sandstone and silt', 'C' => 'Basalt and granite', 'D' => 'Shale and mudstones'], 'correct' => 'A'],
            26 => ['q' => 'A geologist identifies a non-foliated metamorphic rock that was altered inside a localized area primarily by extreme heat with very little pressure. What type of metamorphism occurred?', 'options' => ['A' => 'Regional Metamorphism', 'B' => 'Clastic Metamorphism', 'C' => 'Contact Metamorphism', 'D' => 'Chemical Metamorphism'], 'correct' => 'C'],
            27 => ['q' => 'Which rock pair is explicitly listed as examples of non-foliated rocks produced by Contact Metamorphism?', 'options' => ['A' => 'Slate and schist', 'B' => 'Gneiss and mudstone', 'C' => 'Quartzite (from sandstone) and marble (from limestone)', 'D' => 'Carbonate and dolomite'], 'correct' => 'C'],
            28 => ['q' => 'Which metamorphic rocks are listed as squashed, foliated examples derived from shale and mudstones under high pressure?', 'options' => ['A' => 'Basalt and Granite', 'B' => 'Slate, schist, and gneiss', 'C' => 'Limestone and dolomite', 'D' => 'Sandstone and marble'], 'correct' => 'B'],
            29 => ['q' => 'According to the foundational pathways of the Rock Cycle, what serves as the primary starting point of all processes?', 'options' => ['A' => 'Sedimentary rocks', 'B' => 'Metamorphic rocks', 'C' => 'Igneous rocks', 'D' => 'Glacial debris'], 'correct' => 'C'],
            30 => ['q' => 'Which process involves a mechanical wedging effect caused by repeated cycles of water freezing and thawing inside fractures?', 'options' => ['A' => 'Exfoliation', 'B' => 'Frost wedging', 'C' => 'Root Penetration', 'D' => 'Hydration'], 'correct' => 'B'],
            31 => ['q' => 'How is mechanical "Exfoliation" defined?', 'options' => ['A' => 'Deep tree roots growing directly into open rock fractures.', 'B' => 'Carbonic acid dissolving subterranean minerals to form wide caves.', 'C' => 'The spalling or peeling off of layers of rock because of pressure.', 'D' => 'Soil debris slowly creeping down a low-gradient hillside.'], 'correct' => 'C'],
            32 => ['q' => 'Chemical weathering includes "Hydration". According to the text, what occurs during hydration?', 'options' => ['A' => 'Oxygen reacts with metals to form a deep red rust layer.', 'B' => 'Minerals dissolve or combine with water, forming clay minerals.', 'C' => 'Rock faces mechanically peel away in curved sheets.', 'D' => 'Glaciers physically push weathered sediments downward.'], 'correct' => 'B'],
            33 => ['q' => 'Which of the following is a form of chemical weathering that occurs when carbon dioxide dissolves in water, creating an acid that breaks down rock minerals?', 'options' => ['A' => 'Frost wedging', 'B' => 'Exfoliation', 'C' => 'Carbonation', 'D' => 'Oxidation'], 'correct' => 'C'],
            34 => ['q' => 'How does Erosion differ fundamentally from Weathering?', 'options' => ['A' => 'Weathering involves downslope gravity movement; Erosion breaks rocks down chemically.', 'B' => 'Weathering is the breaking down of rock; Erosion is the process of physically removing those weathered materials by agents like wind and water.', 'C' => 'Weathering requires glaciers; Erosion only happens via atmospheric wind patterns.', 'D' => 'There is no difference; they are perfectly interchangeable synonyms.'], 'correct' => 'B'],
            35 => ['q' => 'What are the three explicit types of landslides listed under Fast Mass Wasting?', 'options' => ['A' => 'Creep, Solifluction, and Slump', 'B' => 'Frost wedging, Exfoliation, and Root penetration', 'C' => 'Rockslide, Slump, and Mudflows', 'D' => 'Oxidation, Carbonation, and Hydration'], 'correct' => 'C'],
            36 => ['q' => 'The principle stating that "the present is the key to the past"-meaning that the natural laws operating today have been constant throughout geologic time-is known as:', 'options' => ['A' => 'The Principle of Superposition', 'B' => 'The Principle of Cross-cutting Relationships', 'C' => 'Relative Dating', 'D' => 'Uniformitarianism'], 'correct' => 'D'],
            37 => ['q' => 'What does the Law of Superposition declare about an undisturbed sedimentary sequence?', 'options' => ['A' => 'Sediments are always deposited in completely vertical columns.', 'B' => 'An intrusive rock layer is always younger than the rock it cuts into.', 'C' => 'Each layer is younger than the layer beneath it and older than the layer above it.', 'D' => 'Rocks containing carbon-14 are automatically positioned at the base.'], 'correct' => 'C'],
            38 => ['q' => 'If an igneous rock intrusion cuts directly through several pre-existing sedimentary layers, which law determines that the intrusion is the younger feature?', 'options' => ['A' => 'Principle of Original Horizontality', 'B' => 'Principle of Superposition', 'C' => 'Principle of Cross-cutting Relationships', 'D' => 'Radiometric Carbon-14 Dating'], 'correct' => 'C'],
            39 => ['q' => 'What specific material is measured using Absolute Carbon-14 Dating?', 'options' => ['A' => 'Organic remains in ancient samples', 'B' => 'Granitic strata zones in the continental crust', 'C' => 'Silicate structures inside basaltic rocks', 'D' => 'Salinity levels inside ocean ridges'], 'correct' => 'A'],
            40 => ['q' => 'Geologists divide Earth\'s history into organized structural units. What is the correct hierarchy of the Geologic Time Scale, moving from the largest unit of time down to smaller subdivisions?', 'options' => ['A' => 'Epoch -> Period -> Era -> Eons', 'B' => 'Eons -> Era -> Periods -> Epoch', 'C' => 'Cenozoic -> Mesozoic -> Paleozoic', 'D' => 'Phanerozoic -> Precambrian -> Proterozoic -> Archean -> Hadean'], 'correct' => 'B'],
            41 => ['q' => 'Which Era within the Phanerozoic Eon is explicitly annotated as the "age of reptiles"?', 'options' => ['A' => 'Paleozoic Era', 'B' => 'Mesozoic Era', 'C' => 'Cenozoic Era', 'D' => 'Phanerozoic Eon'], 'correct' => 'B'],
            42 => ['q' => 'The Earth\'s atmosphere consists of a specific blend of gases. What are its three primary components by volume?', 'options' => ['A' => '78% Oxygen, 21% Nitrogen, 1% Carbon Dioxide', 'B' => '78% Nitrogen, 21% Oxygen, 1% Argon', 'C' => '50% Hydrogen, 40% Helium, 10% Oxygen', 'D' => '97% Saltwater, 3% Freshwater, 1% Water Vapor'], 'correct' => 'B'],
            43 => ['q' => 'Match the atmospheric layer to its correct temperature trend and physical characteristic:', 'options' => ['A' => 'Troposphere: Hottest overall layer; temperature increases with altitude.', 'B' => 'Stratosphere: Contains the ozone layer; temperature increases with altitude.', 'C' => 'Mesosphere: Weather occurs here; contains 80% of total atmospheric mass.', 'D' => 'Thermosphere: Coldest region of the atmosphere; temperature decreases with altitude.'], 'correct' => 'B'],
            44 => ['q' => 'What is the precise name given to the upper boundary interface of the troposphere?', 'options' => ['A' => 'Stratopause', 'B' => 'Mesopause', 'C' => 'Tropopause', 'D' => 'Ionosphere'], 'correct' => 'C'],
            45 => ['q' => 'Where is the Ionosphere located, and what is its primary function?', 'options' => ['A' => 'Located in the troposphere; it generates local sea breezes.', 'B' => 'Located in the thermosphere and upper mesosphere; it contains free electrons/ions that reflect radio waves.', 'C' => 'Located in the exosphere; it transitions directly into a vacuum.', 'D' => 'Located in the core; it separates solid and liquid metals.'], 'correct' => 'B'],
            46 => ['q' => 'Local coastal wind patterns change between day and night due to differential heating. Which statement accurately describes a Sea Breeze?', 'options' => ['A' => 'It occurs at night when air moves from the cooled land surfaces out to the sea.', 'B' => 'It occurs during the day when warm air over the land expands and rises, drawing cooler, denser air from the sea inward.', 'C' => 'It is an artificial rainmaking technique initialized using dry-ice pellets.', 'D' => 'It is a high-altitude cloud development pattern containing heavy nimbus properties.'], 'correct' => 'B'],
            47 => ['q' => 'Which cloud form matches the descriptive category "layer; stratified, or layered forms"?', 'options' => ['A' => 'Cirrus', 'B' => 'Cumulus', 'C' => 'Stratus', 'D' => 'Nimbus'], 'correct' => 'C'],
            48 => ['q' => 'Which vertical development cloud is explicitly associated with rain and thunderstorm production?', 'options' => ['A' => 'Altocumulus', 'B' => 'Cirrostratus', 'C' => 'Cumulonimbus', 'D' => 'Nimbostratus'], 'correct' => 'C'],
            49 => ['q' => 'Which type of precipitation is defined as "frozen rain, or pellets of ice, that occurs when rain falls through a cold surface layer of air and freezes"?', 'options' => ['A' => 'Sleet', 'B' => 'Hail', 'C' => 'Snow', 'D' => 'Frost'], 'correct' => 'A'],
            50 => ['q' => 'According to the "Trivia" note, which two materials are commonly used in artificial rainmaking (cloud seeding)?', 'options' => ['A' => 'Sodium ions and chloride ions', 'B' => 'Carbonic acid and peridotite fragments', 'C' => 'Silver iodide crystals and dry-ice pellets', 'D' => 'Magnesium silicates and basalt dust'], 'correct' => 'C'],
            51 => ['q' => 'What are the two most abundant ions by percentage dissolved in ocean water?', 'options' => ['A' => 'Sulfate (7.68%) and Magnesium (3.69%)', 'B' => 'Carbonate (55.05%) and Potassium (30.61%)', 'C' => 'Chloride ions (55.05%) and Sodium ions (30.61%)', 'D' => 'Silicon (55.05%) and Aluminum (30.61%)'], 'correct' => 'C'],
            52 => ['q' => 'Groundwater movement through subsurface soil and rock layers is primarily regulated by two distinct physical properties. What are they?', 'options' => ['A' => 'Salinity (mass of dissolved salts) and Chloride ion concentration.', 'B' => 'Porosity (capacity to store water) and Permeability (capacity to transmit fluids).', 'C' => 'Condensation (vapor freezing) and Evaporation rates.', 'D' => 'Clastic configuration and Foliation spacing.'], 'correct' => 'B'],
        ];
    }

    public function index()
    {
        $questions = $this->getQuestions();
        return view('quiz', compact('questions'));
    }

    public function submit(Request $request)
    {
        $questions = $this->getQuestions();
        $answers = $request->input('answers', []);
        $score = 0;
        $results = [];

        foreach ($questions as $id => $data) {
            $userAnswer = $answers[$id] ?? null;
            $isCorrect = ($userAnswer === $data['correct']);
            
            if ($isCorrect) {
                $score++;
            }

            $results[$id] = [
                'question' => $data['q'],
                'options' => $data['options'],
                'user_answer' => $userAnswer,
                'correct_answer' => $data['correct'],
                'is_correct' => $isCorrect
            ];
        }

        return view('result', compact('score', 'results', 'questions'));
    }
}